---
version: "3"
services:
 devopsdb:
   image: mailcheck571/docker:dbimage
   ports:
     - "3306:3306"

 application:
   image: mailcheck571/docker:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
